namespace MultiplayerARPG.HeroEditor4D
{
    public enum EHeroEditorItemPart
    {
        None,
        Armor,
        Helmet,
        Shield,
        Melee1H,
        Melee2H,
        Bow,
        Crossbow,
        Firearm1H,
        Supplies,
        Body,
        Ears,
        Eyebrows,
        Eyes,
        Hair,
        Beard,
        Mouth,
        Makeup,
        Mask,
        Earrings,
        Vest,
        Bracers,
        Leggings,
        Cape,
        Back,
        Count
    }
}
